// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsX1t1aT9PRtX3c2vZxqP1u7j9EeEXVuA',
    appId: '1:470887069414:web:c2302faf76f5678461ed27',
    messagingSenderId: '470887069414',
    projectId: 'socialapptest-511b9',
    authDomain: 'socialapptest-511b9.firebaseapp.com',
    storageBucket: 'socialapptest-511b9.firebasestorage.app',
    measurementId: 'G-004D16D5QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIM9CGluQRuKq8OYptWkj7AE1ql6ubtTs',
    appId: '1:470887069414:android:d093ec4d2d7a6ee661ed27',
    messagingSenderId: '470887069414',
    projectId: 'socialapptest-511b9',
    storageBucket: 'socialapptest-511b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_n9oXPj06nCWs1g8U0RuQnXgixeXlhHM',
    appId: '1:470887069414:ios:5867cd1da20ca31161ed27',
    messagingSenderId: '470887069414',
    projectId: 'socialapptest-511b9',
    storageBucket: 'socialapptest-511b9.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaAppTest',
  );
}
